# Generated by Django 4.2.5 on 2023-11-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_model',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz_submission',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
