# Generated by Django 4.2.5 on 2023-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_model_max_attempts_quiz_submission_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_model',
            name='subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Math', 'Math'), ('Science', 'Science'), ('History', 'History')], default='Reading', max_length=20),
        ),
    ]
