# Generated by Django 4.2.5 on 2023-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_history_grade_account_math_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='history_letter_grade',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='math_letter_grade',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='reading_letter_grade',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='science_letter_grade',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
    ]
