# Generated by Django 4.2.5 on 2023-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_history_letter_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='history_letter_grade',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='math_letter_grade',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='reading_letter_grade',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='science_letter_grade',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
    ]
